proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=REPORTS:10m max_size=1g inactive=7d use_temp_path=off;

server {
  listen 80;
  server_name _;

  # CDN URL: http://localhost:8088/reports/<objectKey>
  location /reports/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # убрать CORS заголовки от Minio, чтобы не было "двойного"
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Methods;
    proxy_hide_header Access-Control-Allow-Headers;

    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    add_header Access-Control-Allow-Headers "*" always;

    proxy_cache REPORTS;
    proxy_cache_key $scheme$proxy_host$request_uri;
    proxy_cache_valid 200 206 30d;
    proxy_cache_valid 404 1m;
    add_header X-Cache-Status $upstream_cache_status always;

    proxy_pass http://minio:9000/bionicpro-reports/;
  }
}
